rss:
  - name: TechCrunch
    url: https://techcrunch.com/feed/

  - name: AWS News
    url: https://aws.amazon.com/blogs/aws/feed/

  - name: Azure Dev Blog
    url: https://devblogs.microsoft.com/azure-sdk/feed/

  - name: Zenn
    url: https://zenn.dev/feed